#!/bin/sh
set -e

# Remove cron entry
rm -f /etc/cron.d/sysusage

# Remove httpd.conf entry
rm -f /etc/apache2/conf.d/httpd-sysusage.conf
perl -p -i -e 's/^(.*httpd-sysusage.conf.*)/#$1/' /etc/apache2/httpd.conf

# Remove data entries
rm -rf /var/lib/sysusage

# Remove HTML output
rm -rf /usr/share/apache2/sysusage

exit 0
